version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "test-0:1:1,test-1:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
      - "2181:2181"

  nginx:
      image: jwilder/nginx-proxy
      volumes:
        # It needs to access Docker's API, so we mount the Unix socket
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
      # Listens on port 80, accessed by our host on http://localhost
      ports:
        - "9000:80"

  remora:
    image: registry.opensource.zalan.do/buffalo/remora
    depends_on:
      - kafka
    hostname: remora
    environment:
      KAFKA_ENDPOINT: "kafka:9092"
      VIRTUAL_HOST: 'localhost'
    expose:
      - 9000
